apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    run: my-nginx 
spec:
  containers:
    - name: myweb
      #image: twalter/openshift-nginx:latest 
      image: bitnami/nginx
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
